export const environment = {
  production: false,
  userApiUrl: "http://localhost:8092/users",
  registerURL: "",
  userLoginUrl: "login",
  sellerLoginUrl: "seller-login",
  sellerRegister: "seller",
  activateUser: "activate",
  addAddress: "address",

  wishlistApiUrl: "http://localhost:8091/wishlist",
  addToWishlist: "",
  addToWishlistWithUser: "user",
  getWishList: "allWishlist",
  getUserWishlist: "user-wishlist",
  deleteWishlist: "",
  deleteUserWishlist: "user-remove",

  bookApiUrl: "http://localhost:8091/books",
  getBooksList: "",
  getSellerBookList: "seller",
  addbook: "",
  addBookImage: "upload",

  cartApiUrl: "http://localhost:8091/orders",
  addToBag: "",
  addToCartWithUser: "user",
  cartList: "cart",
  userCartList: "user-cart",
  deleteOrder: "remove-order",
  updateQuantity: "",
  confirmOrder: "confirm",
};
