export const environment = {
  production: false,
  userApiUrl: "http://localhost:9002/users",
  registerURL: "",
  userLoginUrl: "login",
  sellerLoginUrl: "seller-login",
  sellerRegister: "seller",
  activateUser: "activate",
  addAddress: "address",

  bookApiUrl: "http://localhost:9002/books",
  getBooksList: "",
  getSellerBookList: "seller",
  addbook: "",
  addBookImage: "upload",

  cartApiUrl: "http://localhost:8091/orders",
  addToBag: "",
  addToCartWithUser: "user",
  cartList: "cart",
  userCartList: "user-cart",
  deleteOrder: "remove-order",
  updateQuantity: "",
  confirmOrder: "confirm",
};
